export const AUTH_TOKEN_EXPIRES_TIMEOUT = 365 * 24 * 60 * 60 * 1000;

export const WEBSOCKET_RECONNECT_TIMEOUT = 5000;

export const PLAYER_PREVIOUS_RESET_TIMEOUT = 2500;
export const PLAYER_SEEK_TIME = 10;
export const PLAYER_UPDATE_UI_TIMEOUT = 100;
export const PLAYER_UPDATE_SERVER_TIMEOUT = 5000;
