name: server-lint
run-name: ${{ github.actor }} is linting the server codebase
on:
  push:
    branches:
      - master
    paths:
      - "server/**"
  pull_request:
    branches:
      - master
    paths:
      - "server/**"
permissions:
  contents: read
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - run: cd server
      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
