name: web-lint
run-name: ${{ github.actor }} is linting the web codebase
on:
  push:
    branches:
      - master
    paths:
      - "web/**"
  pull_request:
    branches:
      - master
    paths:
      - "web/**"
permissions:
  contents: read
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
